default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     localhost
  database: nusredcross_development
  username: <%= ENV['PSQL_USERNAME'] %>
  password: <%= ENV['PSQL_PASSWORD'] %>
  template: template0

test:
  <<: *default
  host:     localhost
  database: nusredcross_test
  username: <%= ENV['PSQL_USERNAME'] %>
  password: <%= ENV['PSQL_PASSWORD'] %>
  template: template0

production:
  <<: *default
  database: nusredcross_production
  username: nusredcross
  password: <%= ENV['SPIDERMAN_DATABASE_PASSWORD'] %>

